sudo: false

matrix:
  include:

  - os: linux
    language: python
    python: 2.7
    before_install:
    - cd python
    # command to install dependencies
    install: 
    - pip install -r requirements.txt
    # command to run tests
    script: nosetest 
    env: TRAVIS_LANG=python

  - os: linux
    language: python
    python: 3.4
    before_install:
    - cd python
    # command to install dependencies
    install: 
    - pip install -r requirements.txt
    # command to run tests
    script: nosetest 
    env: TRAVIS_LANG=python

  - os: linux
    language: python
    python: 3.5
    before_install:
    - cd python
    # command to install dependencies
    install: 
    - pip install -r requirements.txt
    # command to run tests
    script: nosetest 
    env: TRAVIS_LANG=python

  - os: linux
    language: r
    cache: packages
    before_install:
    - cd R
    after_success:
    - Rscript -e 'install.packages("covr"); covr::codecov()'
    env: TRAVIS_LANG=R

